<?php
require_once 'auth.php';
checkLogin();

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'error' => 'Invalid method']);
    exit;
}

$tpl = $_POST['tpl'] ?? '';
if (!$tpl) {
    echo json_encode(['success' => false, 'error' => 'Missing template name']);
    exit;
}

$configFile = __DIR__ . '/../template/' . $tpl . '/config.json';
$tplDir = __DIR__ . '/../template/' . $tpl;

// 1. Prepare Config Data
$data = [
    'qr' => [
        'x' => intval($_POST['qr']['x']),
        'y' => intval($_POST['qr']['y']),
        'size' => intval($_POST['qr']['size'])
    ],
    'bank_name' => [
        'x' => intval($_POST['bank_name']['x']),
        'y' => intval($_POST['bank_name']['y']),
        'size' => intval($_POST['bank_name']['size']),
        'color' => $_POST['bank_name']['color'],
        'align' => 'left',
        'font' => 'default'
    ],
    'acc_num' => [
        'x' => intval($_POST['acc_num']['x']),
        'y' => intval($_POST['acc_num']['y']),
        'size' => intval($_POST['acc_num']['size']),
        'color' => $_POST['acc_num']['color'],
        'align' => 'left',
        'font' => 'default'
    ]
    // Add more fields if needed
];

// 2. Save Config JSON
if (file_put_contents($configFile, json_encode($data, JSON_PRETTY_PRINT))) {

    // 3. Update index.php (Smart Template Logic)
    // We overwrite index.php to ensure it uses the new TemplateRenderer with this config
    // This makes sure both OLD and NEW templates eventually use the same robust logic

    $indexContent = '<?php
// Smart Template Loader
// Generated by Admin Panel

require_once "../../admin/TemplateRenderer.php";

$config = json_decode(file_get_contents(__DIR__ . "/config.json"), true);
$renderer = new TemplateRenderer(__DIR__, $config);
$renderer->render();
?>';

    file_put_contents($tplDir . '/index.php', $indexContent);

    echo json_encode(['success' => true]);
} else {
    echo json_encode(['success' => false, 'error' => 'Failed to write config file']);
}
