<?php
// Smart Template Loader
// Generated by Admin Panel

require_once "../../admin/TemplateRenderer.php";

$config = json_decode(file_get_contents(__DIR__ . "/config.json"), true);
$renderer = new TemplateRenderer(__DIR__, $config);
$renderer->render();
?>